# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15a100014b1a2dafb8aab13dd48ba291169b3109b9e1939441b43a020bb2e06dc87cfd5d739dbc2cde8ce1db3c8837df3d687b45a652298b9209ffdd404ebcfa

test:
  secret_key_base: eb5bdcf2c974ea3a6f224c3a1ea73c8246a6053968a9476e20ee64a0e80f0821ea562de3069c1e0114983194c40cc4618d6f0da4181fd0fe5111a83ad967018e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
